<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $faker = Faker\Factory::create();
        DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh bông lan trứng muối I', 
            'slug'=> 'banh-bong-lan-trung-moi-i',  
            'content' => 'Bánh bông lan trứng muối I',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'banh-man-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh bông lan trứng muối II', 
            'slug'=> 'banh-bong-lan-trung-moi-ii',  
            'content' => 'Bánh bông lan trứng muối II',
            'unit_price'=> '110000',
            'discount_price'=>'100000',
            'image'=>'banh-man-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh French', 
            'slug'=> 'banh-french',  
            'content' => 'Bánh French',
            'unit_price'=> '120000',
            'discount_price'=>'110000',
            'image'=>'banh-man-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh mì Australia', 
            'slug'=> 'banh-mi-australia',  
            'content' => 'Bánh mì Australia',
            'unit_price'=> '150000',
            'discount_price'=>'135000',
            'image'=>'banh-man-1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh mặn thập cẩm', 
            'slug'=> 'banh-man-thap-cam',  
            'content' => 'Bánh mặn thập cẩm',
            'unit_price'=> '100000',
            'discount_price'=>'90000',
            'image'=>'banh-man-5.png',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh Muffins trứng', 
            'slug'=> 'banh-muffins-trung',  
            'content' => 'Bánh Muffins trứng',
            'unit_price'=> '120000',
            'discount_price'=>'100000',
            'image'=>'banh-man-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
            DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh Scone Peach Cake', 
            'slug'=> 'banh-scone-peach-cake',  
            'content' => 'ánh Scone Peach Cake',
            'unit_price'=> '120000',
            'discount_price'=>'100000',
            'image'=>'banh-man-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 1,
           'name'=> 'Bánh mì Loaf I', 
            'slug'=> 'banh-mi-loaf-i',  
            'content' => 'Bánh mì Loaf I',
            'unit_price'=> '130000',
            'discount_price'=>'120000',
            'image'=>'banh-man-8.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh ngọt nhân cream táo', 
            'slug'=> 'banh-ngot-nhan-cream-tao',  
            'content' => 'Bánh ngọt nhân cream táo',
            'unit_price'=> '125000',
            'discount_price'=>'120000',
            'image'=>'banh-ngot-1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh Chocolate Trái cây', 
            'slug'=> 'banh-chocolate-trai-cay',  
            'content' => 'Bánh Chocolate Trái cây',
            'unit_price'=> '135000',
            'discount_price'=>'120000',
            'image'=>'banh-ngot-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh Chocolate Trái cây II', 
            'slug'=> 'banh-chocolate-trai-cay-ii',  
            'content' => 'Bánh Chocolate Trái cây II',
            'unit_price'=> '145000',
            'discount_price'=>'120000',
            'image'=>'banh-ngot-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Peach Cake', 
            'slug'=> 'peach-cake',  
            'content' => 'Peach Cake',
            'unit_price'=> '155000',
            'discount_price'=>'130000',
            'image'=>'banh-ngot-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh Macaron Pháp', 
            'slug'=> 'banh-macaron-phap',  
            'content' => 'Bánh Macaron Pháp',
            'unit_price'=> '165000',
            'discount_price'=>'150000',
            'image'=>'banh-ngot-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh Tiramisu-Italia', 
            'slug'=> 'banh-tiramisu-italia',  
            'content' => 'Bánh Tiramisu-Italia',
            'unit_price'=> '185000',
            'discount_price'=>'160000',
            'image'=>'banh-ngot-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 2,
           'name'=> 'Bánh Táo-Mỹ', 
            'slug'=> 'Banh-tao-my',  
            'content' => 'Bánh Táo-Mỹ',
            'unit_price'=> '175000',
            'discount_price'=>'160000',
            'image'=>'banh-ngot-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);

         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh Gato Trái cây Việt Quất', 
            'slug'=> 'banh-gato-trai-cay-viet-quat',  
            'content' => 'Bánh Gato Trái cây Việt Quất',
            'unit_price'=> '185000',
            'discount_price'=>'160000',
            'image'=>'banh-trai-cay-1.png',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh sinh nhật rau câu trái cây', 
            'slug'=> 'banh-sinh-nhat-rau-cau-trai-cây',  
            'content' => 'Bánh sinh nhật rau câu trái cây',
            'unit_price'=> '135000',
            'discount_price'=>'110000',
            'image'=>'banh-trai-cay-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh kem Chocolate Dâu', 
            'slug'=> 'banh-kem-chocolate-dau',  
            'content' => 'Bánh kem Chocolate Dâu',
            'unit_price'=> '125000',
            'discount_price'=>'115000',
            'image'=>'banh-trai-cay-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh kem Dâu III', 
            'slug'=> 'banh-kem-dau-iii',  
            'content' => 'Bánh kem Dâu III',
            'unit_price'=> '135000',
            'discount_price'=>'125000',
            'image'=>'banh-trai-cay-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh kem Dâu I', 
            'slug'=> 'banh-kem-dau-i',  
            'content' => 'Bánh kem Dâu I',
            'unit_price'=> '115000',
            'discount_price'=>'100000',
            'image'=>'banh-trai-cay-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Bánh trái cây II', 
            'slug'=> 'banh-trai-cay-ii',  
            'content' => 'Bánh trái cây II',
            'unit_price'=> '145000',
            'discount_price'=>'125000',
            'image'=>'banh-trai-cay-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 3,
           'name'=> 'Apple Cake', 
            'slug'=> 'apple-cake',  
            'content' => 'Apple Cake',
            'unit_price'=> '175000',
            'discount_price'=>'165000',
            'image'=>'banh-trai-cay-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         



         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Trái cây I', 
            'slug'=> 'banh-kem-trai-cay-i',  
            'content' => 'Bánh kem Trái cây I',
            'unit_price'=> '165000',
            'discount_price'=>'145000',
            'image'=>'banh-kem-1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Trái cây II', 
            'slug'=> 'banh-kem-trai-cay-ii',  
            'content' => 'Bánh kem Trái cây II',
            'unit_price'=> '145000',
            'discount_price'=>'115000',
            'image'=>'banh-kem-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Doraemon', 
            'slug'=> 'banh-kem-doraemon',  
            'content' => 'Bánh kem Doraemon',
            'unit_price'=> '165000',
            'discount_price'=>'135000',
            'image'=>'banh-kem-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Caramen Pudding', 
            'slug'=> 'banh-kem-caramen-pudding',  
            'content' => 'Bánh kem Caramen Pudding',
            'unit_price'=> '205000',
            'discount_price'=>'195000',
            'image'=>'banh-kem-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Chocolate Fruit', 
            'slug'=> 'banh-kem-chocolate-fruit',  
            'content' => 'Bánh kem Chocolate Fruit',
            'unit_price'=> '145000',
            'discount_price'=>'130000',
            'image'=>'banh-kem-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Mango Mouse', 
            'slug'=> 'banh-kem-mango-mouse',  
            'content' => 'Bánh kem Mango Mouse',
            'unit_price'=> '125000',
            'discount_price'=>'120000',
            'image'=>'banh-kem-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Matcha Mouse', 
            'slug'=> 'banh-kem-matcha-mouse',  
            'content' => 'Bánh kem Matcha Mouse',
            'unit_price'=> '135000',
            'discount_price'=>'120000',
            'image'=>'banh-kem-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Flower Fruit', 
            'slug'=> 'banh-kem-flower-fruit',  
            'content' => 'Bánh kem Flower Fruit',
            'unit_price'=> '115000',
            'discount_price'=>'100000',
            'image'=>'banh-kem-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Strawberry Delight', 
            'slug'=> 'banh-kem-strawberry-delight',  
            'content' => 'Bánh kem Strawberry Delight',
            'unit_price'=> '185000',
            'discount_price'=>'180000',
            'image'=>'banh-kem-8.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 4,
           'name'=> 'Bánh kem Raspberry Delight', 
            'slug'=> 'banh-kem-raspberry-delight',  
            'content' => 'Bánh kem Raspberry Delight',
            'unit_price'=> '165000',
            'discount_price'=>'150000',
            'image'=>'banh-kem-9.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);



         DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Sầu riêng', 
            'slug'=> 'banh-crepe-sau-rieng',  
            'content' => 'Bánh Crepe Sầu riêng',
            'unit_price'=> '135000',
            'discount_price'=>'130000',
            'image'=>'banh-crepe-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Sầu riêng-Chuối', 
            'slug'=> 'banh-crepe-sau-rieng-chuối',  
            'content' => 'Bánh Crepe Sầu riêng-Chuối',
            'unit_price'=> '155000',
            'discount_price'=>'130000',
            'image'=>'banh-crepe-1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
         DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Dâu', 
            'slug'=> 'banh-crepe-dau',  
            'content' => 'Bánh Crepe Dâu',
            'unit_price'=> '160000',
            'discount_price'=>'140000',
            'image'=>'banh-crepe-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
        DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Pháp', 
            'slug'=> 'banh-crepe-phap',  
            'content' => 'Bánh Crepe Pháp',
            'unit_price'=> '140000',
            'discount_price'=>'130000',
            'image'=>'banh-crepe-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
          DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Táo', 
            'slug'=> 'banh-crepe-tao',  
            'content' => 'Bánh Crepe Táo',
            'unit_price'=> '140000',
            'discount_price'=>'140000',
            'image'=>'banh-crepe-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Trà xanh', 
            'slug'=> 'banh-crepe-tra-xanh',  
            'content' => 'Bánh Crepe Trà xanh',
            'unit_price'=> '120000',
            'discount_price'=>'110000',
            'image'=>'banh-crepe-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Sầu riêng và Dứa', 
            'slug'=> 'banh-crepe-sau-rieng-va-dua',  
            'content' => 'Bánh Crepe Sầu riêng và Dứa',
            'unit_price'=> '140000',
            'discount_price'=>'135000',
            'image'=>'banh-crepe-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);

           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Chocolate', 
            'slug'=> 'banh-crepe-chocolate',  
            'content' => 'Bánh Crepe Sầu riêng và Dứa',
            'unit_price'=> '140000',
            'discount_price'=>'135000',
            'image'=>'banh-crepe-8.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 5,
           'name'=> 'Bánh Crepe Đào', 
            'slug'=> 'banh-crepe-dao',  
            'content' => 'Bánh Crepe Đào',
            'unit_price'=> '130000',
            'discount_price'=>'125000',
            'image'=>'banh-crepe-9.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);


            DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Beefy Pizza', 
            'slug'=> 'beefy-pizza',  
            'content' => 'Beefy Pizza',
            'unit_price'=> '180000',
            'discount_price'=>'160000',
            'image'=>'pizza-1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Hawaii Pizza', 
            'slug'=> 'hawaii-pizza',  
            'content' => 'Hawaii Pizza',
            'unit_price'=> '170000',
            'discount_price'=>'160000',
            'image'=>'pizza-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
              DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Smoke Chicken Pizza', 
            'slug'=> 'smoke-chicken-pizza',  
            'content' => 'Smoke Chicken Pizza',
            'unit_price'=> '150000',
            'discount_price'=>'150000',
            'image'=>'pizza-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Sausage Pizza', 
            'slug'=> 'sausage-pizza',  
            'content' => 'Sausage Pizza',
            'unit_price'=> '140000',
            'discount_price'=>'135000',
            'image'=>'pizza-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
               DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Ocean Pizza', 
            'slug'=> 'ocean-pizza',  
            'content' => 'Ocean Pizza',
            'unit_price'=> '160000',
            'discount_price'=>'155000',
            'image'=>'pizza-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'All Meaty Pizza', 
            'slug'=> 'all-meaty-pizza',  
            'content' => 'All Meaty Pizza',
            'unit_price'=> '150000',
            'discount_price'=>'150000',
            'image'=>'pizza-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
              DB::table('products')->insert([
           'category_id'=> 6,
           'name'=> 'Tuna Pizza', 
            'slug'=> 'tuna-pizza',  
            'content' => 'Tuna Pizza',
            'unit_price'=> '185000',
            'discount_price'=>'1750000',
            'image'=>'pizza-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);



            DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem nhân dừa', 
            'slug'=> 'banh-su-kem-nhan-dua',  
            'content' => 'Bánh su kem nhân dừa',
            'unit_price'=> '195000',
            'discount_price'=>'1750000',
            'image'=>'banh-su-kem-1.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
            DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem sữa tươi', 
            'slug'=> 'banh-su-kem-sua-tuoi',  
            'content' => 'Bánh su kem sữa tươi',
            'unit_price'=> '175000',
            'discount_price'=>'1750000',
            'image'=>'banh-su-kem-2.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem sữa tươi chiên giòn', 
            'slug'=> 'banh-su-kem-sua-tuoi-chien-gion',  
            'content' => 'Bánh su kem sữa tươi chiên giòn',
            'unit_price'=> '155000',
            'discount_price'=>'1450000',
            'image'=>'banh-su-kem-3.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
            DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem dâu sữa tươi', 
            'slug'=> 'banh-su-kem-dau-sua-tuoi',  
            'content' => 'Bánh su kem dâu sữa tươi',
            'unit_price'=> '140000',
            'discount_price'=>'130000',
            'image'=>'banh-su-kem-4.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem bơ sữa tươi', 
            'slug'=> 'banh-su-kem-bo-sua-tuoi',  
            'content' => 'Bánh su kem bơ sữa tươi',
            'unit_price'=> '130000',
            'discount_price'=>'130000',
            'image'=>'banh-su-kem-5.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
             DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem nhân trái cây sữa tươi', 
            'slug'=> 'banh-su-kem-nhan-trai-cay-sua-tuoi',  
            'content' => 'Bánh su kem nhân trái cây sữa tươi',
            'unit_price'=> '120000',
            'discount_price'=>'110000',
            'image'=>'banh-su-kem-6.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem cà phê', 
            'slug'=> 'banh-su-kem-ca-phe',  
            'content' => 'Bánh su kem cà phê',
            'unit_price'=> '125000',
            'discount_price'=>'120000',
            'image'=>'banh-su-kem-7.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem phô mai', 
            'slug'=> 'banh-su-kem-pho-mai',  
            'content' => 'Bánh su kem phô mai',
            'unit_price'=> '145000',
            'discount_price'=>'130000',
            'image'=>'banh-su-kem-8.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
           DB::table('products')->insert([
           'category_id'=> 7,
           'name'=> 'Bánh su kem sữa tươi chocolate', 
            'slug'=> 'banh-su-kem-sua-tuoi-chocolate',  
            'content' => 'Bánh su kem sữa tươi chocolate',
            'unit_price'=> '155000',
            'discount_price'=>'140000',
            'image'=>'banh-su-kem-9.jpg',
            'quantity'=>'20',
            'status'=>rand(0,1),
            'created_at' => date("Y-m-d"),
            'updated_at' => date("Y-m-d"),
        ]);
    }
}
